name: test
run-name: ${{github.actor}} is running tests
on:
  [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Setting up dependencies ..."
          cd c/scripts || exit 1
          source setup_dependencies.sh $(nproc) || exit 2
      - run: |
          echo "Building sources ..."
          cd c/scripts || exit 1
          source build.sh $(nproc) || exit 2
      - run: |
          echo "Running tests ..."
          cd c/build || exit 1
          ctest -V || exit 2
          echo "Successfully ran all tests."

          
